/**
 * Re-export central de ícones Lucide.
 *
 * Os apps importam SEMPRE daqui (`@papopro/ui/icons`), nunca direto de
 * `lucide-react`. Centralizar permite:
 *  - padronizar tamanho/stroke default no futuro;
 *  - tree-shake só os ícones realmente usados;
 *  - trocar a biblioteca sem refatorar 300 imports espalhados.
 */
export {
  Activity,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  AtSign,
  Bell,
  Building2,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  CircleDot,
  Clock,
  Copy,
  Download,
  Edit,
  ExternalLink,
  File,
  FileText,
  Filter,
  Flame,
  Gauge,
  Globe,
  HelpCircle,
  Home,
  Inbox,
  Info,
  KanbanSquare,
  Keyboard,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  List,
  ListChecks,
  Loader2,
  LogOut,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Paperclip,
  Phone,
  PieChart,
  Plus,
  PlusCircle,
  Repeat,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Smartphone,
  Smile,
  Sparkles,
  Star,
  Sun,
  Tag,
  ThermometerSnowflake,
  ThermometerSun,
  Trash2,
  Upload,
  User,
  UserPlus,
  Users,
  Wifi,
  WifiOff,
  X,
  Zap,
} from 'lucide-react';

export type { LucideIcon, LucideProps } from 'lucide-react';
